baseurl = "https://vignette.md/"
title = "vignette"
author = "Georgios Karamanis"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "renga"

enableEmoji = true
hasCJKLanguage = true

googleAnalytics = "UA-727326-26"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "vignette"
faviconfile = "images/favicon.png"
logofile = "images/logo.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "gkaramanis/Rprofile_net"
twitter = "vignette_md"
email = "vignette@karaman.is"

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "interviews"
name = "Interviews"
url = "/interviews/"
weight = 2

[[menu.primary]]
identifier = "contribute"
name = "Contribute"
url = "/contribute/"
weight = 3
